name: docs
on:
    # 每当 push 到 main 分支时触发部署
    push:
        branches: [master]
    # 手动触发部署
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: Install pnpm
              uses: pnpm/action-setup@v2.0.1
              id: pnpm-install
              with:
                version: 7
                run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            # 运行构建脚本
            - name: Build VuePress site
              run: pnpm docs:build

            # 发布到 Github Pages 默认分支
            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  # 部署到 gh-pages 分支
                  target_branch: gh-pages
                  # 部署目录为 VuePress 的默认输出目录
                  build_dir: docs/.vuepress/dist
              env:
                  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
